import React, { useEffect, useState, useRef } from 'react';
import {View, Text, FlatList, Image, Pressable, ActivityIndicator, TouchableOpacity, Animated, Easing, StatusBar} from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation, useRoute, RouteProp } from '@react-navigation/native';
import { LinearGradient } from 'expo-linear-gradient';
import { RootStackParamList } from '../../App';
import axios from '../../context/axiosConfig';
import Ionicons from "@expo/vector-icons/Ionicons";
import * as Print from 'expo-print';
import { shareAsync } from 'expo-sharing';
import socket from '../../utils/socket';
import { Alert } from '../ui/AlertModal';

type ScreenRouteProp = RouteProp<RootStackParamList, 'LeaderboardScreen'>;

const LeaderboardScreen = () => {
  const route = useRoute<ScreenRouteProp>();
  const navigation = useNavigation<any>();
  const { roomId, myScore } = route.params;

  const [leaders, setLeaders] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);

  // Animation value for the refresh icon
  const spinAnim = useRef(new Animated.Value(0)).current;

  // 2. SETUP REAL-TIME LISTENERS
  useEffect(() => {
    fetchLeaderboard();

    socket.emit("watch_leaderboard", { roomId });

    const onUpdate = () => {
      console.log("🔔 New submission received! Refreshing...");
      fetchLeaderboard();
    };

    socket.on("leaderboard_updated", onUpdate);

    return () => {
      socket.off("leaderboard_updated", onUpdate);
    };
  }, [roomId]);

  const fetchLeaderboard = async () => {
    try {
      const res = await axios.get(`/quiz/leaderboard/${roomId}`);
      setLeaders(res.data);
    } catch (err) {
      console.log("Error fetching leaderboard", err);
    } finally {
      setLoading(false);
    }
  };

  // Animated Refresh Handler
  const handleManualRefresh = async () => {
    // Start spinning animation
    Animated.loop(
      Animated.timing(spinAnim, {
        toValue: 1,
        duration: 800,
        easing: Easing.linear,
        useNativeDriver: true,
      })
    ).start();

    await fetchLeaderboard();

    // Stop animation when done
    spinAnim.stopAnimation();
    spinAnim.setValue(0);
  };

  // Interpolate rotation value
  const spin = spinAnim.interpolate({
    inputRange: [0, 1],
    outputRange: ['0deg', '360deg']
  });

  const downloadPDF = async () => {
    if (leaders.length === 0) {
      return Alert.alert("Empty", "No data to download.");
    }
    setDownloading(true);
    try {
      const tableRows = leaders.map((item, index) => `
        <tr>
          <td style="text-align: center; color: #374151; font-weight: bold;">${index + 1}</td>
          <td>
             <div style="font-weight: bold; color: #111827;">${item.user?.name || "Unknown"}</div>
             <div style="font-size: 11px; color: #6b7280;">@${item.user?.username || "unknown"}</div>
          </td>
          <td style="text-align: center; font-weight: 900; font-size: 16px; color: #ec4899;">${item.score}</td>
        </tr>
      `).join('');

      // Formatted PDF for light mode printing (since PDFs are usually printed on white paper)
      const html = `
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
            <style>
              body { font-family: 'Helvetica', sans-serif; padding: 40px; background: #ffffff; }
              h1 { text-align: center; color: #ec4899; margin-bottom: 5px; font-weight: 900; text-transform: uppercase; letter-spacing: 2px;}
              h3 { text-align: center; color: #6b7280; font-weight: normal; margin-top: 0; }
              table { width: 100%; border-collapse: collapse; margin-top: 30px; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }
              th, td { border-bottom: 1px solid #e5e7eb; padding: 16px 20px; text-align: left; }
              th { background-color: #111827; color: #ffffff; font-weight: bold; text-transform: uppercase; font-size: 12px; letter-spacing: 1px;}
              tr:last-child td { border-bottom: none; }
              .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #9ca3af; }
            </style>
          </head>
          <body>
            <h1>Leaderboard Results</h1>
            <h3>Room ID: ${roomId}</h3>

            <table>
              <thead>
                <tr>
                  <th style="width: 10%; text-align: center;">Rank</th>
                  <th>Participant</th>
                  <th style="width: 15%; text-align: center;">Score</th>
                </tr>
              </thead>
              <tbody>
                ${tableRows}
              </tbody>
            </table>

            <div class="footer">
              Generated by Fync App • ${new Date().toLocaleDateString()}
            </div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      await shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });

    } catch (error) {
      console.error("PDF Generation Error:", error);
      Alert.alert("Error", "Could not generate PDF. Please try again.");
    } finally {
      setDownloading(false);
    }
  };

  const renderItem = ({ item, index }: { item: any; index: number }) => {
    // Styling for Top 3 Ranks
    let rankColor = 'text-slate-500';
    let iconColor = '#94a3b8';
    let cardBg = 'bg-white';
    if (index === 0) { rankColor = 'text-yellow-600'; iconColor = '#d97706'; cardBg = 'bg-amber-50/50'; } // Gold
    else if (index === 1) { rankColor = 'text-slate-500'; iconColor = '#64748b'; cardBg = 'bg-slate-50/50'; } // Silver
    else if (index === 2) { rankColor = 'text-orange-600'; iconColor = '#c2410c'; cardBg = 'bg-orange-50/50'; } // Bronze

    return (
      <View className={`flex-row items-center ${cardBg} p-5 mb-4 mx-6 rounded-3xl border border-slate-100 shadow-sm shadow-black/5`}>
        {/* Rank */}
        <View className="w-10 items-center justify-center mr-3">
          {index < 3 ? (
            <Ionicons name="trophy" size={28} color={iconColor} />
          ) : (
            <Text className={`text-xl font-black  ${rankColor}`}>#{index + 1}</Text>
          )}
        </View>

        {/* Avatar */}
        <View className="w-14 h-14 bg-white rounded-2xl mr-4 border border-slate-100 justify-center items-center shadow-sm overflow-hidden p-1">
          {item.user?.avatar ? (
            <Image source={{ uri: item.user.avatar }} className="w-full h-full rounded-xl" />
          ) : (
            <Text className="font-black  text-slate-300 text-xl">{item.user?.username?.[0]?.toUpperCase()}</Text>
          )}
        </View>

        {/* User Info */}
        <View className="flex-1">
          <Text className="font-black  text-slate-900 text-base uppercase tracking-tight" numberOfLines={1}>
            {item.user?.name || item.user?.username || "Global User"}
          </Text>
          <Text className="text-2xs text-slate-500 font-bold uppercase tracking-wide mt-0.5">@{item.user?.username || "unknown"}</Text>
        </View>

        {/* Score Badge */}
        <View className="bg-pink-50 px-4 py-2 rounded-2xl shadow-sm border border-pink-100 transform rotate-2">
          <Text className="font-black  text-pink-500 text-base">
            {item.score} <Text className="text-2xs uppercase tracking-tighter">Pts</Text>
          </Text>
        </View>
      </View>
    );
  };

  return (
    <View className="flex-1 bg-[#F8FAFC]">
      <StatusBar barStyle="dark-content" />

      <SafeAreaView className="flex-1">
        {/* HEADER */}
        <View className="flex-row items-center justify-between px-8 pt-8 mb-4">
          <TouchableOpacity
            onPress={() => navigation.navigate("Tabs")}
            className="w-12 h-12 bg-white rounded-2xl items-center justify-center border border-slate-100 shadow-sm shadow-black/5"
          >
            <Ionicons name="home" size={20} color="#18181b" />
          </TouchableOpacity>

          <Text className="text-3xl font-black  text-slate-900 tracking-tighter uppercase">
            Leader<Text className="text-pink-500">Board</Text>
          </Text>

          {/* ACTION BUTTONS */}
          <View className="flex-row items-center gap-3">
            {/* Animated Refresh Button */}
            <TouchableOpacity onPress={handleManualRefresh} className="w-12 h-12 bg-white rounded-2xl items-center justify-center border border-slate-100 shadow-sm shadow-black/5">
              <Animated.View style={{ transform: [{ rotate: spin }] }}>
                <Ionicons name="refresh" size={20} color="#18181b" />
              </Animated.View>
            </TouchableOpacity>

            {/* Download Button */}
            <TouchableOpacity onPress={downloadPDF} disabled={downloading} className="w-12 h-12 bg-pink-500 rounded-2xl items-center justify-center shadow-lg shadow-pink-500/20">
              {downloading ? (
                <ActivityIndicator size="small" color="white" />
              ) : (
                <Ionicons name="download" size={20} color="white" />
              )}
            </TouchableOpacity>
          </View>
        </View>

        {/* Room ID Badge */}
        <View className="items-center mb-8">
          <View className="bg-white px-6 py-2 rounded-full border border-slate-100 shadow-sm shadow-black/5">
            <Text className="text-2xs font-black  text-slate-500 tracking-wide uppercase">Node: <Text className="text-slate-900">{roomId}</Text></Text>
          </View>
        </View>

        {/* User's Own Score Card (If played) */}
        {myScore !== undefined && (
          <View className="mx-8 bg-white p-8 rounded-5xl mb-8 shadow-2xl shadow-black/5 items-center overflow-hidden border border-slate-100">
            <View className="absolute top-0 right-0 w-32 h-32 bg-pink-500/5 rounded-full -mr-16 -mt-16" />
            <Text className="text-pink-500 font-black  text-2xs uppercase tracking-wide mb-2">My Final Ranking</Text>
            <Text className="text-slate-900 text-6xl font-black  tracking-tighter">{myScore}</Text>
            <Text className="text-slate-500 font-black  text-2xs uppercase tracking-wide mt-2">Points Verified</Text>
          </View>
        )}

        {/* Leaderboard List */}
        {loading ? (
          <ActivityIndicator size="large" color="#f97316" className="mt-20" />
        ) : (
          <FlatList
            data={leaders}
            keyExtractor={(item) => item._id}
            renderItem={renderItem}
            showsVerticalScrollIndicator={false}
            contentContainerStyle={{ paddingBottom: 40 }}
            ListEmptyComponent={
              <View className="items-center justify-center mt-20 px-10">
                <View className="w-20 h-20 bg-slate-50 rounded-4xl items-center justify-center mb-6">
                  <Ionicons name="people" size={40} color="#CBD5E1" />
                </View>
                <Text className="text-slate-900 font-black  text-xl tracking-tight text-center uppercase">Dev Void</Text>
                <Text className="text-slate-500 text-center font-bold text-xs mt-2 uppercase tracking-wide">
                  Awaiting entry from challengers.
                </Text>
              </View>
            }
          />
        )}
      </SafeAreaView>
    </View>
  );
};

export default LeaderboardScreen;
