import React, { useEffect, useState, useRef } from 'react';
import { 
  View, Text, FlatList, Image, Pressable, ActivityIndicator, Alert, 
  TouchableOpacity, Animated, Easing 
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation, useRoute, RouteProp } from '@react-navigation/native';
import { LinearGradient } from 'expo-linear-gradient';
import { RootStackParamList } from '../../App';
import axios from '../../context/axiosConfig';
import Ionicons from "@expo/vector-icons/Ionicons";
import * as Print from 'expo-print';
import { shareAsync } from 'expo-sharing';
import socket from '../../utils/socket'; 

type ScreenRouteProp = RouteProp<RootStackParamList, 'LeaderboardScreen'>;

const LeaderboardScreen = () => {
  const route = useRoute<ScreenRouteProp>();
  const navigation = useNavigation<any>();
  const { roomId, myScore } = route.params;

  const [leaders, setLeaders] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);

  // Animation value for the refresh icon
  const spinAnim = useRef(new Animated.Value(0)).current;

  // 2. SETUP REAL-TIME LISTENERS
  useEffect(() => {
    fetchLeaderboard();

    socket.emit("watch_leaderboard", { roomId });

    const onUpdate = () => {
        console.log("🔔 New submission received! Refreshing...");
        fetchLeaderboard(); 
    };

    socket.on("leaderboard_updated", onUpdate);

    return () => {
        socket.off("leaderboard_updated", onUpdate);
    };
  }, [roomId]);

  const fetchLeaderboard = async () => {
    try {
      const res = await axios.get(`/quiz/leaderboard/${roomId}`);
      setLeaders(res.data);
    } catch (err) {
      console.log("Error fetching leaderboard", err);
    } finally {
      setLoading(false);
    }
  };

  // Animated Refresh Handler
  const handleManualRefresh = async () => {
    // Start spinning animation
    Animated.loop(
      Animated.timing(spinAnim, {
        toValue: 1,
        duration: 800,
        easing: Easing.linear,
        useNativeDriver: true,
      })
    ).start();

    await fetchLeaderboard();

    // Stop animation when done
    spinAnim.stopAnimation();
    spinAnim.setValue(0);
  };

  // Interpolate rotation value
  const spin = spinAnim.interpolate({
    inputRange: [0, 1],
    outputRange: ['0deg', '360deg']
  });

  const downloadPDF = async () => {
    if (leaders.length === 0) {
      return Alert.alert("Empty", "No data to download.");
    }
    setDownloading(true);
    try {
      const tableRows = leaders.map((item, index) => `
        <tr>
          <td style="text-align: center; color: #374151; font-weight: bold;">${index + 1}</td>
          <td>
             <div style="font-weight: bold; color: #111827;">${item.user?.name || "Unknown"}</div>
             <div style="font-size: 11px; color: #6b7280;">@${item.user?.username || "unknown"}</div>
          </td>
          <td style="text-align: center; font-weight: 900; font-size: 16px; color: #ec4899;">${item.score}</td>
        </tr>
      `).join('');

      // Formatted PDF for light mode printing (since PDFs are usually printed on white paper)
      const html = `
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
            <style>
              body { font-family: 'Helvetica', sans-serif; padding: 40px; background: #ffffff; }
              h1 { text-align: center; color: #ec4899; margin-bottom: 5px; font-weight: 900; text-transform: uppercase; letter-spacing: 2px;}
              h3 { text-align: center; color: #6b7280; font-weight: normal; margin-top: 0; }
              table { width: 100%; border-collapse: collapse; margin-top: 30px; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }
              th, td { border-bottom: 1px solid #e5e7eb; padding: 16px 20px; text-align: left; }
              th { background-color: #111827; color: #ffffff; font-weight: bold; text-transform: uppercase; font-size: 12px; letter-spacing: 1px;}
              tr:last-child td { border-bottom: none; }
              .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #9ca3af; }
            </style>
          </head>
          <body>
            <h1>Leaderboard Results</h1>
            <h3>Room ID: ${roomId}</h3>
            
            <table>
              <thead>
                <tr>
                  <th style="width: 10%; text-align: center;">Rank</th>
                  <th>Participant</th>
                  <th style="width: 15%; text-align: center;">Score</th>
                </tr>
              </thead>
              <tbody>
                ${tableRows}
              </tbody>
            </table>

            <div class="footer">
              Generated by Fync App • ${new Date().toLocaleDateString()}
            </div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      await shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });

    } catch (error) {
      console.error("PDF Generation Error:", error);
      Alert.alert("Error", "Could not generate PDF. Please try again.");
    } finally {
      setDownloading(false);
    }
  };

  const renderItem = ({ item, index }: { item: any; index: number }) => {
    // Styling for Top 3 Ranks
    let rankColor = 'text-gray-500';
    let iconColor = '#6b7280';
    if (index === 0) { rankColor = 'text-yellow-400'; iconColor = '#facc15'; } // Gold
    else if (index === 1) { rankColor = 'text-gray-300'; iconColor = '#d1d5db'; } // Silver
    else if (index === 2) { rankColor = 'text-orange-400'; iconColor = '#fb923c'; } // Bronze

    return (
      <View className="flex-row items-center bg-[#1e1e1e]/80 p-4 mb-3 mx-6 rounded-2xl border border-white/10 shadow-lg">
        {/* Rank */}
        <View className="w-10 items-center justify-center mr-2">
           {index < 3 ? (
               <Ionicons name="trophy" size={24} color={iconColor} />
           ) : (
               <Text className={`text-lg font-bold ${rankColor}`}>#{index + 1}</Text>
           )}
        </View>
        
        {/* Avatar */}
        <View className="w-12 h-12 bg-gray-800 rounded-full mr-4 border border-white/10 justify-center items-center overflow-hidden">
          {item.user?.avatar ? (
            <Image source={{ uri: item.user.avatar }} className="w-full h-full" />
          ) : (
            <Text className="font-bold text-gray-400 text-lg">{item.user?.username?.[0]?.toUpperCase()}</Text>
          )}
        </View>

        {/* User Info */}
        <View className="flex-1">
            <Text className="font-bold text-white text-base" numberOfLines={1}>
            {item.user?.name || item.user?.username || "Unknown"}
            </Text>
            <Text className="text-xs text-gray-500">@{item.user?.username}</Text>
        </View>

        {/* Score Badge */}
        <View className="bg-pink-500/20 px-3 py-1.5 rounded-full border border-pink-500/30">
          <Text className="font-black text-pink-500">{item.score} <Text className="font-medium text-[10px]">pts</Text></Text>
        </View>
      </View>
    );
  };

  return (
    <View className="flex-1 bg-black">
      {/* Background Gradient */}
      <LinearGradient colors={['rgba(236, 72, 153, 0.4)', 'rgba(0,0,0,0.85)', '#000000']} className="absolute w-full h-full" />

      <SafeAreaView className="flex-1">
        {/* HEADER */}
        <View className="flex-row items-center justify-between px-6 pt-4 mb-2">
          <TouchableOpacity 
            onPress={() => navigation.navigate("Tabs")}
            className="p-2 bg-white/10 rounded-full border border-white/10"
          >
            <Ionicons name="home" size={20} color="white" />
          </TouchableOpacity>
          
          <Text className="text-2xl font-black italic text-white tracking-tighter">
             LEADER<Text className="text-pink-500">BOARD</Text> 🏆
          </Text>
          
          {/* ACTION BUTTONS */}
          <View className="flex-row items-center gap-3">
            {/* Animated Refresh Button */}
            <TouchableOpacity onPress={handleManualRefresh} className="p-2 bg-white/10 rounded-full border border-white/10">
                <Animated.View style={{ transform: [{ rotate: spin }] }}>
                    <Ionicons name="refresh" size={20} color="white" />
                </Animated.View>
            </TouchableOpacity>

            {/* Download Button */}
            <TouchableOpacity onPress={downloadPDF} disabled={downloading} className="p-2 bg-pink-600 rounded-full border border-pink-500/50">
                {downloading ? (
                    <ActivityIndicator size="small" color="white" />
                ) : (
                    <Ionicons name="cloud-download-outline" size={20} color="white" />
                )}
            </TouchableOpacity>
          </View>
        </View>

        {/* Room ID Badge */}
        <View className="items-center mb-6">
            <View className="bg-[#2a2a2a] px-4 py-1.5 rounded-full border border-white/10">
                <Text className="text-xs font-bold text-gray-400 tracking-widest uppercase">Room: <Text className="text-white">{roomId}</Text></Text>
            </View>
        </View>

        {/* User's Own Score Card (If played) */}
        {myScore !== undefined && (
          <View className="mx-6 bg-pink-600/20 p-6 rounded-3xl mb-6 border border-pink-500/50 items-center shadow-lg">
            <Text className="text-pink-200 font-bold text-xs uppercase tracking-widest mb-1">Your Final Score</Text>
            <Text className="text-white text-5xl font-black italic">{myScore}</Text>
          </View>
        )}

        {/* Leaderboard List */}
        {loading ? (
          <ActivityIndicator size="large" color="#ec4899" className="mt-20" />
        ) : (
          <FlatList
            data={leaders}
            keyExtractor={(item) => item._id}
            renderItem={renderItem}
            showsVerticalScrollIndicator={false}
            contentContainerStyle={{ paddingBottom: 20 }}
            ListEmptyComponent={
              <View className="items-center justify-center mt-20 opacity-50">
                  <Ionicons name="hourglass-outline" size={48} color="gray" />
                  <Text className="text-center text-gray-400 mt-4 font-bold text-lg">Waiting for challengers...</Text>
              </View>
            }
          />
        )}
      </SafeAreaView>
    </View>
  );
};

export default LeaderboardScreen;