import { Tool } from './Common';

export const TOOLS: Tool[] = [
    { id: 'regex', title: 'Regex-Architect', description: 'Visual Pattern Builder for students.', icon: 'code-slash-outline', color: ['#8b5cf6', '#6d28d9'], category: 'Development' },
    { id: 'readme', title: 'ReadMe-Gen', description: 'GitHub README.md Generator.', icon: 'document-text-outline', color: ['#10b981', '#059669'], category: 'Development' },
    { id: 'api-play', title: 'API Playground', description: 'JSONPlaceholder-style REST client.', icon: 'rocket-outline', color: ['#f59e0b', '#d97706'], category: 'Development' },
    { id: 'type-gen', title: 'API-to-Type', description: 'JSON to TypeScript/Java/Dart.', icon: 'construct-outline', color: ['#3b82f6', '#1d4ed8'], category: 'Development' },
    { id: 'unit-conv', title: 'Dev Converter', description: 'PX to REM, Unix Time, Hex to RGBA.', icon: 'swap-horizontal-outline', color: ['#ec4899', '#be185d'], category: 'Utility' },
    { id: 'commit', title: 'Commit-Gen', description: 'Conventional Commit Message Builder.', icon: 'git-commit-outline', color: ['#6366f1', '#4338ca'], category: 'DevOps' },
    { id: 'cron', title: 'Crontab-Visualizer', description: 'Human-friendly Cron schedules.', icon: 'time-outline', color: ['#14b8a6', '#0d9488'], category: 'DevOps' },
    { id: 'sql-nosql', title: 'SQL-to-NoSQL', description: 'Translate MySQL to MongoDB.', icon: 'shuffle-outline', color: ['#ec4899', '#9d174d'], category: 'Development' },
    { id: 'vault', title: 'Cloud-Vault', description: 'Secure Secret Management.', icon: 'shield-checkmark-outline', color: ['#ef4444', '#b91c1c'], category: 'DevOps' },
    { id: 'css-viz', title: 'Flex & Grid', description: 'Interactive layout playground.', icon: 'layers-outline', color: ['#f59e0b', '#b45309'], category: 'Design' },
    { id: 'compress', title: 'Asset-Compressor', description: 'Tiny WebP or optimized SVG.', icon: 'contract-outline', color: ['#3b82f6', '#2563eb'], category: 'Design' },
    { id: 'contract-scaffold', title: 'Solidity Scaffold', description: 'No-Code ERC20 Smart Contract.', icon: 'document-lock-outline', color: ['#6366f1', '#4338ca'], category: 'Development' },
    { id: 'og-preview', title: 'OG Previewer', description: 'Simulate social media link cards.', icon: 'logo-whatsapp', color: ['#25d366', '#128c7e'], category: 'Design' },
    { id: 'git-master', title: 'Git-Master', description: 'Comprehensive Git command reference.', icon: 'git-branch-outline', color: ['#ef4444', '#b91c1c'], category: 'Utility' },
    { id: 'linux-master', title: 'Linux-Master', description: 'Ultimate Linux CLI handbook.', icon: 'terminal', color: ['#f59e0b', '#d97706'], category: 'Utility' },
    { id: 'architect', title: 'The Architect', description: 'System design decision tree.', icon: 'business-outline', color: ['#3b82f6', '#1d4ed8'], category: 'DevOps' },
    { id: 'term-to-eng', title: 'Terminal Explainer', description: 'Translate scripts to English.', icon: 'terminal-outline', color: ['#10b981', '#059669'], category: 'Utility' },
    { id: 'cost', title: 'Cloud-Cost', description: 'AWS/GCP/Azure/DO Estimator.', icon: 'calculator-outline', color: ['#10b981', '#047857'], category: 'DevOps' },
    { id: 'sig-gen', title: 'API-Signature', description: 'HMAC & SHA-256 Generator.', icon: 'key-outline', color: ['#ef4444', '#991b1b'], category: 'DevOps' },
    { id: 'curl-code', title: 'CURL-to-Code', description: 'cURL to Fetch/Axios snippets.', icon: 'terminal-outline', color: ['#8b5cf6', '#6d28d9'], category: 'Development' },
    { id: 'svg-comp', title: 'SVG-to-React', description: 'SVG to React/Flutter components.', icon: 'logo-react', color: ['#6366f1', '#3730a3'], category: 'Development' },
    { id: 'code-img', title: 'Code-to-Image', description: 'Beautiful code snippets for social.', icon: 'image-outline', color: ['#f43f5e', '#e11d48'], category: 'Design' },
    { id: 'contrast', title: 'Contrast-Validator', description: 'WCAG Accessibility scores.', icon: 'eye-outline', color: ['#14b8a6', '#0f766e'], category: 'Design' },
    { id: 'sla', title: 'SLA-Calculator', description: 'Uptime percentage visualizer.', icon: 'trending-up-outline', color: ['#f43f5e', '#be123c'], category: 'DevOps' },
    { id: 'mock', title: 'Fync Mock', description: 'JSON Mocking tool.', icon: 'cube-outline', color: ['#ec4899', '#be185d'], category: 'Development' },
];

export const REGEX_LIB = [
    { name: 'Email (Basic)', pattern: '^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$', cat: 'Auth' },
    { name: 'Email (Strict)', pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$', cat: 'Auth' },
    { name: 'Strong Password', pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$', cat: 'Auth' },
    { name: 'Username (4-16)', pattern: '^[a-zA-Z0-9_]{4,16}$', cat: 'Auth' },
    { name: 'Full Name', pattern: '^[a-zA-Z\\s]{2,50}$', cat: 'Auth' },
    { name: 'Phone (India)', pattern: '^(\\+91[\\-\\s]?)?[0]?(91)?[6789]\\d{9}$', cat: 'Location' },
    { name: 'Phone (US)', pattern: '^(\\+?1[\\-\\s]?)?\\(?[2-9]\\d{2}\\)?[\\-\\s]?\\d{3}[\\-\\s]?\\d{4}$', cat: 'Location' },
    { name: 'Phone (UK)', pattern: '^(((\\+44\\s?\\d{4}|\\(?0\\d{4}\\)?)\\s?\\d{3}\\s?\\d{3})|((\\+44\\s?\\d{3}|\\(?0\\d{3}\\)?)\\s?\\d{3}\\s?\\d{4})|((\\+44\\s?\\d{2}|\\(?0\\d{2}\\)?)\\s?\\d{4}\\s?\\d{4}))$', cat: 'Location' },
    { name: 'URL (Web)', pattern: 'https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)', cat: 'Identifier' },
    { name: 'IPv4 Address', pattern: '^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$', cat: 'Dev' },
    { name: 'IPv6 Address', pattern: '^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$', cat: 'Dev' },
    { name: 'MAC Address', pattern: '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$', cat: 'Dev' },
    { name: 'Hex Color', pattern: '^#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$', cat: 'Design' },
    { name: 'UUID', pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$', cat: 'Identifier' },
    { name: 'MongoDB ID', pattern: '^[0-9a-fA-F]{24}$', cat: 'Dev' },
    { name: 'Credit Card (Visa)', pattern: '^4[0-9]{12}(?:[0-9]{3})?$', cat: 'Finance' },
    { name: 'Credit Card (MC)', pattern: '^5[1-5][0-9]{14}$', cat: 'Finance' },
    { name: 'JWT Token', pattern: '^[A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+\\.?[A-Za-z0-9-_.+/=]*$', cat: 'Auth' },
    { name: 'Date (YYYY-MM-DD)', pattern: '^\\d{4}-\\d{2}-\\d{2}$', cat: 'Misc' },
    { name: 'Date (DD/MM/YYYY)', pattern: '^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$', cat: 'Misc' },
    { name: 'Time (24h)', pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$', cat: 'Misc' },
    { name: 'Slug', pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$', cat: 'Identifier' },
    { name: 'Semantic Version', pattern: '^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$', cat: 'Dev' },
    { name: 'Git Commit Hash', pattern: '^[0-9a-f]{7,40}$', cat: 'Dev' },
    { name: 'Digits Only', pattern: '^\\d+$', cat: 'Misc' },
    { name: 'Letters Only', pattern: '^[a-zA-Z]+$', cat: 'Misc' },
    { name: 'Price (USD)', pattern: '^\\$?\\d+(\\.\\d{2})?$', cat: 'Finance' },
    { name: 'Camel Case', pattern: '^[a-z]+(?:[A-Z][a-z]*)*$', cat: 'Code' },
    { name: 'Pascal Case', pattern: '^[A-Z][a-z]+(?:[A-Z][a-z]*)*$', cat: 'Code' },
    { name: 'Snake Case', pattern: '^[a-z]+(?:_[a-z]+)*$', cat: 'Code' },
    { name: 'HTML Tag', pattern: '^<([a-z1-6]+)([^>]+)*(?:>(.*)<\\/\\1>|\\s+\\/>)$', cat: 'Code' },
    { name: 'US Zip Code', pattern: '^\\d{5}(?:[-\\s]\\d{4})?$', cat: 'Location' },
    { name: 'UK Postcode', pattern: '^([A-Z][A-HJ-Y]?\\d[A-Z\\d]? \\d[A-Z]{2}|GIR 0AA)$', cat: 'Location' },
    { name: 'India PIN Code', pattern: '^[1-9][0-9]{5}$', cat: 'Location' },
    { name: 'SSN (US)', pattern: '^\\d{3}-\\d{2}-\\d{4}$', cat: 'Finance' },
    { name: 'Latitude', pattern: '^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?)$', cat: 'Location' },
    { name: 'Longitude', pattern: '^[-+]?(180(\\.0+)?|((1[0-7]\\d)|([1-9]?\\d))(\\.\\d+)?)$', cat: 'Location' },
    { name: 'Base64', pattern: '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$', cat: 'Dev' },
    { name: 'ASCII Only', pattern: '^[\\x00-\\x7F]*$', cat: 'Misc' },
    { name: 'Binary', pattern: '^[01]+$', cat: 'Dev' },
    { name: 'Octal', pattern: '^[0-7]+$', cat: 'Dev' },
    { name: 'Hexadecimal', pattern: '^[0-9a-fA-F]+$', cat: 'Dev' },
    { name: 'C Identifier', pattern: '^[a-zA-Z_][a-zA-Z0-9_]*$', cat: 'Code' },
    { name: 'Docker Image', pattern: '^([a-z0-9]+(?:[._-][a-z0-9]+)*\\/)?([a-z0-9]+(?:[._-][a-z0-9]+)*)(?::[a-z0-9]+(?:[._-][a-z0-9]+)*)?$', cat: 'Dev' },
    { name: 'GitHub Repo', pattern: '^[a-zA-Z0-9-]+\\/[a-zA-Z0-9._-]+$', cat: 'Dev' },
    { name: 'ISBN-10', pattern: '^(?:\\d[\\ |-]?){9}[\\d|X]$', cat: 'Misc' },
    { name: 'ISBN-13', pattern: '^(?:\\d[\\ |-]?){13}$', cat: 'Misc' },
    { name: 'YouTube URL', pattern: '^(?:https?:\\/\\/)?(?:www\\.)?(?:youtube\\.com\\/watch\\?v=|youtu\\.be\\/)([\\w-]{11})(?:&.*)?$', cat: 'Misc' },
    { name: 'CSS Comment', pattern: '^\\/\\*[\\s\\S]*?\\*\\/$', cat: 'Code' },
    { name: 'JS single comment', pattern: '^\\/\\/.*$', cat: 'Code' },
    { name: 'MD ImageLink', pattern: '!\\[.*?\\]\\(.*?\\)', cat: 'Code' },
    { name: 'MD HyperLink', pattern: '\\[.*?\\]\\(.*?\\)', cat: 'Code' },
    { name: 'CSV Line', pattern: '^([^,]*)(,[^,]*)*$', cat: 'Misc' },
    { name: 'Apache Log', pattern: '^(\\S+) (\\S+) (\\S+) \\[([\\w:/]+\\s[+\\-]\\d{4})\\] "(\\S+)\\s?(\\S+)?\\s?(\\S+)?" (\\d{3}|-) (\\d+|-)$', cat: 'Dev' },
    { name: 'SemVer Regex', pattern: '^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$', cat: 'Dev' },
    { name: 'Word Count (Min 5)', pattern: '^(\\w+\\W+){4,}\\w+$', cat: 'Misc' },
    { name: 'No Special Chars', pattern: '^[a-zA-Z0-9]+$', cat: 'Auth' },
    { name: 'Indian Pan Card', pattern: '^[A-Z]{5}[0-9]{4}[A-Z]{1}$', cat: 'Location' },
    { name: 'GST Number', pattern: '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', cat: 'Finance' },
    { name: 'Adhaar Card', pattern: '^[2-9]{1}[0-9]{3}\\s[0-9]{4}\\s[0-9]{4}$', cat: 'Location' },
    { name: 'Vehicle Number', pattern: '^[A-Z]{2}[0-9]{2}[A-Z]{2}[0-9]{4}$', cat: 'Location' },
    { name: 'Credit Card (Amex)', pattern: '^3[47][0-9]{13}$', cat: 'Finance' },
    { name: 'Credit Card (Disc)', pattern: '^6(?:011|5[0-9]{2})[0-9]{12}$', cat: 'Finance' },
    { name: 'Twitter Handler', pattern: '^@?(\\w){1,15}$', cat: 'Misc' },
    { name: 'Instagram User', pattern: '^[a-zA-Z0-9._]{1,30}$', cat: 'Misc' },
    { name: 'LinkedIn URL', pattern: '^https?:\\/\\/(www\\.)?linkedin\\.com\\/(in|pub|company)\\/[a-zA-Z0-9_-]+\\/?$', cat: 'Misc' },
    { name: 'BitCoin Address', pattern: '^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$', cat: 'Finance' },
    { name: 'Ethereum Address', pattern: '^0x[a-fA-F0-9]{40}$', cat: 'Finance' },
    { name: 'ASIN (Amazon)', pattern: '^B[0-9A-Z]{9}$', cat: 'Identifier' },
    { name: 'MAC Address IEEE', pattern: '^([0-9A-F]{2}-){5}[0-9A-F]{2}$', cat: 'Dev' },
    { name: 'Discord ID', pattern: '^\\d{17,19}$', cat: 'Identifier' },
    { name: 'Slack Hook URL', pattern: '^https:\\/\\/hooks\\.slack\\.com\\/services\\/[A-Z0-9]+\\/[A-Z0-9]+\\/[A-Z0-9]+$', cat: 'Dev' },
    { name: 'Mongo Connection', pattern: '^mongodb(?:\\+srv)?\\:\\/\\/.+$', cat: 'Dev' },
    { name: 'Redis Connection', pattern: '^redis(?:s)?\\:\\/\\/.+$', cat: 'Dev' },
    { name: 'Cron Exp (Basic)', pattern: '^(\\d+|\\*) (\\d+|\\*) (\\d+|\\*) (\\d+|\\*) (\\d+|\\*)$', cat: 'Dev' },
    { name: 'Port Number', pattern: '^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$', cat: 'Dev' },
    { name: 'File Extension', pattern: '^\\.(\\w+)$', cat: 'Misc' },
    { name: 'Alpha-Numeric (Spc)', pattern: '^[a-zA-Z0-9 ]+$', cat: 'Misc' },
    { name: 'Lowercase Only', pattern: '^[a-z]+$', cat: 'Misc' },
    { name: 'Uppercase Only', pattern: '^[A-Z]+$', cat: 'Misc' },
    { name: 'Strong Name', pattern: '^[A-Z][a-z]+(?: [A-Z][a-z]+)*$', cat: 'Misc' },
    { name: 'Windows Path', pattern: '^[a-zA-Z]:\\\\(?:[^\\\\/:*?"<>|\\r\\n]+\\\\)*[^\\\\/:*?"<>|\\r\\n]*$', cat: 'Misc' },
    { name: 'Unix Path', pattern: '^\\/(?:[^\\/\\0]+\\/)*[^\\/\\0]*$', cat: 'Misc' },
    { name: 'ISBN-13 No Hyphen', pattern: '^\\d{13}$', cat: 'Misc' },
    { name: 'EAN-13', pattern: '^\\d{13}$', cat: 'Misc' },
    { name: 'UPC-A', pattern: '^\\d{12}$', cat: 'Misc' },
    { name: 'Swift Code', pattern: '^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$', cat: 'Finance' },
    { name: 'IBAN Number', pattern: '^[A-Z]{2}\\d{2}[A-Z0-9]{11,30}$', cat: 'Finance' },
    { name: 'Credit Card CVD', pattern: '^[0-9]{3,4}$', cat: 'Finance' },
    { name: 'US Passport', pattern: '^[a-zA-Z0-9]{9}$', cat: 'Location' },
    { name: 'China Resident ID', pattern: '^\\d{15}|\\d{18}|\\d{17}(\\d|X|x)$', cat: 'Location' },
    { name: 'CSS Hex Colors', pattern: '#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})', cat: 'Design' },
    { name: 'RGB Color', pattern: 'rgb\\(\\s*(\\d{1,3})\\s*,\\s*(\\d{1,3})\\s*,\\s*(\\d{1,3})\\s*\\)', cat: 'Design' },
    { name: 'RGBA Color', pattern: 'rgba\\(\\s*(\\d{1,3})\\s*,\\s*(\\d{1,3})\\s*,\\s*(\\d{1,3})\\s*,\\s*(0|1|0\\.\\d+)\\s*\\)', cat: 'Design' },
    { name: 'HSL Color', pattern: 'hsl\\(\\s*(\\d{1,3})\\s*,\\s*(\\d{1,3}%)\\s*,\\s*(\\d{1,3}%)\\s*\\)', cat: 'Design' },
    { name: 'CamelCase 2', pattern: '^[a-z]+([A-Z][a-z]+)*$', cat: 'Code' },
    { name: 'PascalCase 2', pattern: '^[A-Z][a-z]+([A-Z][a-z]+)*$', cat: 'Code' },
    { name: 'Variable Name', pattern: '^[a-zA-Z_$][a-zA-Z0-9_$]*$', cat: 'Code' },
];

export const CONVERSIONS = [
    { id: 'px-rem', name: 'PX to REM', from: 'Pixels', to: 'REM', base: 16 },
    { id: 'px-em', name: 'PX to EM', from: 'Pixels', to: 'EM', base: 16 },
    { id: 'rem-px', name: 'REM to PX', from: 'REM', to: 'Pixels', base: 16 },
    { id: 'px-vw', name: 'PX to VW', from: 'Pixels', to: 'VW', base: 1920 },
    { id: 'px-vh', name: 'PX to VH', from: 'Pixels', to: 'VH', base: 1080 },
    { id: 'hex-rgb', name: 'HEX to RGBA', from: 'Hex', to: 'RGBA', base: 0 },
    { id: 'byte-mb', name: 'Bytes to MB', from: 'Bytes', to: 'MB', base: 1024 * 1024 },
];

export const GIT_COMMANDS_LIB = [
    { cat: 'Setup', name: 'Initialize Repo', cmd: 'git init', desc: 'Create a new local repository' },
    { cat: 'Setup', name: 'Clone Repo', cmd: 'git clone <url>', desc: 'Download a repository from a remote URL' },
    { cat: 'Config', name: 'Set Username', cmd: 'git config --global user.name "Your Name"', desc: 'Identify yourself globally' },
    { cat: 'Config', name: 'Set Email', cmd: 'git config --global user.email "email@example.com"', desc: 'Identify your email globally' },
    { cat: 'Config', name: 'List Config', cmd: 'git config --list', desc: 'Show all current configurations' },
    { cat: 'Basic', name: 'Status', cmd: 'git status', desc: 'Check state of working directory' },
    { cat: 'Basic', name: 'Add File', cmd: 'git add <file>', desc: 'Stage a specific file' },
    { cat: 'Basic', name: 'Add All', cmd: 'git add .', desc: 'Stage all changes in directory' },
    { cat: 'Basic', name: 'Commit', cmd: 'git commit -m "msg"', desc: 'Record staged changes as a snapshot' },
    { cat: 'Basic', name: 'Remove File', cmd: 'git rm <file>', desc: 'Remove file from working directory & index' },
    { cat: 'Basic', name: 'Rename File', cmd: 'git mv <old> <new>', desc: 'Move/rename file & stage the change' },
    { cat: 'Branching', name: 'List Branches', cmd: 'git branch', desc: 'Show local branches' },
    { cat: 'Branching', name: 'Create Branch', cmd: 'git branch <name>', desc: 'Create a new branch' },
    { cat: 'Branching', name: 'Switch Branch', cmd: 'git checkout <name>', desc: 'Switch to a specific branch' },
    { cat: 'Branching', name: 'New & Switch', cmd: 'git checkout -b <name>', desc: 'Create and jump into new branch' },
    { cat: 'Branching', name: 'Delete Branch', cmd: 'git branch -d <name>', desc: 'Safely delete a branch' },
    { cat: 'Branching', name: 'Force Delete', cmd: 'git branch -D <name>', desc: 'Delete branch even if not merged' },
    { cat: 'Branching', name: 'Merge Branch', cmd: 'git merge <branch>', desc: 'Combine specified branch into current' },
    { cat: 'Remote', name: 'Add Remote', cmd: 'git remote add origin <url>', desc: 'Connect to a remote repository' },
    { cat: 'Remote', name: 'Push (Init)', cmd: 'git push -u origin main', desc: 'Push current branch and set upstream' },
    { cat: 'Remote', name: 'Push Changes', cmd: 'git push', desc: 'Update remote with local commits' },
    { cat: 'Remote', name: 'Pull Changes', cmd: 'git pull', desc: 'Fetch and merge remote changes' },
    { cat: 'Remote', name: 'Fetch Only', cmd: 'git fetch', desc: 'Get remote updates without merging' },
    { cat: 'Remote', name: 'Show Remotes', cmd: 'git remote -v', desc: 'List all connected remote URLs' },
    { cat: 'History', name: 'Review Log', cmd: 'git log', desc: 'Show commit history list' },
    { cat: 'History', name: 'Log (One line)', cmd: 'git log --oneline', desc: 'Compact commit history' },
    { cat: 'History', name: 'File History', cmd: 'git log -p <file>', desc: 'Show changes made to a file' },
    { cat: 'History', name: 'Who Changed?', cmd: 'git blame <file>', desc: 'Annotate file lines with commit info' },
    { cat: 'History', name: 'Show Commit', cmd: 'git show <hash>', desc: 'View details of a specific commit' },
    { cat: 'Stashing', name: 'Save Stash', cmd: 'git stash', desc: 'Temporarily store uncommitted changes' },
    { cat: 'Stashing', name: 'List Stashes', cmd: 'git stash list', desc: 'Show all saved stashes' },
    { cat: 'Stashing', name: 'Pop Stash', cmd: 'git stash pop', desc: 'Apply and remove most recent stash' },
    { cat: 'Stashing', name: 'Apply Stash', cmd: 'git stash apply', desc: 'Apply stash but keep in list' },
    { cat: 'Stashing', name: 'Clear Stash', cmd: 'git stash clear', desc: 'Delete all saved stashes' },
    { cat: 'Undo', name: 'Amend Last', cmd: 'git commit --amend', desc: 'Edit last commit message or content' },
    { cat: 'Undo', name: 'Soft Reset', cmd: 'git reset --soft HEAD~1', desc: 'Undo commit, keep changes staged' },
    { cat: 'Undo', name: 'Mixed Reset', cmd: 'git reset HEAD~1', desc: 'Undo commit, keep changes in workspace' },
    { cat: 'Undo', name: 'Hard Reset', cmd: 'git reset --hard HEAD~1', desc: 'Discard last commit & ALL changes' },
    { cat: 'Undo', name: 'Revert Commit', cmd: 'git revert <hash>', desc: 'Create new commit that reverses a previous one' },
    { cat: 'Undo', name: 'Discard Changes', cmd: 'git checkout -- <file>', desc: 'Restore file to last committed state' },
    { cat: 'Advanced', name: 'Rebase', cmd: 'git rebase <branch>', desc: 'Apply commits onto another base' },
    { cat: 'Advanced', name: 'Cherry Pick', cmd: 'git cherry-pick <hash>', desc: 'Copy a specific commit into current branch' },
    { cat: 'Advanced', name: 'Reflog', cmd: 'git reflog', desc: 'Show local history of state changes' },
    { cat: 'Advanced', name: 'Clean Files', cmd: 'git clean -fd', desc: 'Remove all untracked files & dirs' },
    { cat: 'Advanced', name: 'Submodule Init', cmd: 'git submodule update --init --recursive', desc: 'Initialize submodules if repo has them' },
    { cat: 'Disasters', name: 'Wrong Branch', cmd: 'git stash\ngit checkout ok-branch\ngit stash pop', desc: 'I committed/worked on the wrong branch' },
    { cat: 'Disasters', name: 'Force Pull', cmd: 'git fetch --all\ngit reset --hard origin/main', desc: 'Force local to match remote exactly' },
    { cat: 'Disasters', name: 'Bad Merge', cmd: 'git merge --abort', desc: 'Abort merge with conflicts' },
];

export const LINUX_COMMANDS_LIB = [
    { cat: 'File System', name: 'List Files', cmd: 'ls -la', desc: 'List all files with details and hidden files' },
    { cat: 'File System', name: 'Change Directory', cmd: 'cd <path>', desc: 'Navigate to a specific directory' },
    { cat: 'File System', name: 'Present Directory', cmd: 'pwd', desc: 'Show the current absolute path' },
    { cat: 'File System', name: 'Make Directory', cmd: 'mkdir <name>', desc: 'Create a new folder/directory' },
    { cat: 'File System', name: 'Create File', cmd: 'touch <name>', desc: 'Create a new empty file' },
    { cat: 'File System', name: 'Read File', cmd: 'cat <file>', desc: 'Display entire file content in terminal' },
    { cat: 'File System', name: 'Scroll File', cmd: 'less <file>', desc: 'View file with scrolling support' },
    { cat: 'File System', name: 'Copy File', cmd: 'cp <src> <dest>', desc: 'Copy files or directories' },
    { cat: 'File System', name: 'Move/Rename', cmd: 'mv <src> <dest>', desc: 'Move files or rename them' },
    { cat: 'File System', name: 'Remove File', cmd: 'rm <file>', desc: 'Delete a specific file' },
    { cat: 'File System', name: 'Remove Dir', cmd: 'rm -rf <dir>', desc: 'Forcefully delete a directory and contents' },
    { cat: 'File System', name: 'Find File', cmd: 'find . -name "<name>"', desc: 'Search for files by name' },
    { cat: 'System Info', name: 'Check Specs', cmd: 'uname -a', desc: 'Show kernel and system architecture' },
    { cat: 'System Info', name: 'Disk Space', cmd: 'df -h', desc: 'Show disk usage in human-readable format' },
    { cat: 'System Info', name: 'Directory Size', cmd: 'du -sh <dir>', desc: 'Show total size of a directory' },
    { cat: 'System Info', name: 'Memory Usage', cmd: 'free -m', desc: 'Show RAM usage in Megabytes' },
    { cat: 'System Info', name: 'Uptime', cmd: 'uptime', desc: 'How long the system has been running' },
    { cat: 'Processes', name: 'Active Processes', cmd: 'top', desc: 'Real-time viewer for system processes' },
    { cat: 'Processes', name: 'Better Viewer', cmd: 'htop', desc: 'Interactive and colorful process viewer' },
    { cat: 'Processes', name: 'Find Process', cmd: 'ps aux | grep <name>', desc: 'Search for a running process' },
    { cat: 'Processes', name: 'Kill Process', cmd: 'kill -9 <pid>', desc: 'Forcefully stop a process by ID' },
    { cat: 'Processes', name: 'Port Usage', cmd: 'lsof -i :<port>', desc: 'Check what process is using a port' },
    { cat: 'Networking', name: 'IP Info', cmd: 'ip addr', desc: 'Show all network interface addresses' },
    { cat: 'Networking', name: 'Check Connection', cmd: 'ping <host>', desc: 'Test connectivity to a domain/IP' },
    { cat: 'Networking', name: 'Fetch URL', cmd: 'curl -I <url>', desc: 'Fetch headers from a URL' },
    { cat: 'Networking', name: 'Download File', cmd: 'wget <url>', desc: 'Download a file from the internet' },
    { cat: 'Networking', name: 'DNS Lookup', cmd: 'dig <host>', desc: 'Query DNS records for a domain' },
    { cat: 'Networking', name: 'Route Map', cmd: 'traceroute <host>', desc: 'Trace the path of packets to host' },
    { cat: 'Permissions', name: 'Change Owner', cmd: 'sudo chown <user> <file>', desc: 'Change the owner of a file/dir' },
    { cat: 'Permissions', name: 'Full Access', cmd: 'chmod 777 <file>', desc: 'Grant read, write, execute to everyone' },
    { cat: 'Permissions', name: 'Secure Perms', cmd: 'chmod 644 <file>', desc: 'Owner RW, Others Read only' },
    { cat: 'Permissions', name: 'Execute Perm', cmd: 'chmod +x <file>', desc: 'Make a script/file executable' },
    { cat: 'Permissions', name: 'Become Root', cmd: 'sudo -i', desc: 'Login as the superuser/root' },
    { cat: 'Utilities', name: 'Search Text', cmd: 'grep -r "<text>" .', desc: 'Search text recursively in directory' },
    { cat: 'Utilities', name: 'Stream Editor', cmd: 'sed -i "s/old/new/g" <file>', desc: 'Batch find and replace in file' },
    { cat: 'Utilities', name: 'Text Processor', cmd: "awk '{print $1}' <file>", desc: 'Powerful text column parsing' },
    { cat: 'Utilities', name: 'Zip Folder', cmd: 'tar -czvf <name>.tar.gz <dir>', desc: 'Compress directory into Gzip' },
    { cat: 'Utilities', name: 'Unzip File', cmd: 'tar -xzvf <file>.tar.gz', desc: 'Extract Gzip archive' },
];
