export const BOLLYWOOD_MOVIES = [
  "Shershaah", "Sardar Udham", "Bell Bottom", "Sooryavanshi", "83", "Atrangi Re", "Mimi", "Dhamaka", "Haseen Dillruba", "Pagglait",
  "Gangubai Kathiawadi", "The Kashmir Files", "Bhool Bhulaiyaa 2", "Major", "Rocketry: The Nambi Effect", "Brahmastra: Part One – Shiva", "Vikram Vedha", "Drishyam 2", "Bhediya", "Qala", "Monica, O My Darling", "An Action Hero", "Freddy", "Govinda Naam Mera", "Darlings", "Jugjugg Jeeyo", "Uunchai", "Runway 34", "Jayeshbhai J जोरदार", "Anek",
  "Pathaan", "Tu Jhoothi Main Makkaar", "Mrs. Chatterjee Vs Norway", "Bholaa", "The Kerala Story", "Zara Hatke Zara Bachke", "Satyaprem Ki Katha", "Rocky Aur Rani Kii Prem Kahaani", "Gadar 2", "OMG 2", "Jawan", "Fukrey 3", "Mission Raniganj", "Tiger 3", "Animal", "Sam Bahadur", "Dunki", "Salaar: Part 1 – Ceasefire", "12th Fail", "Merry Christmas",
  "Fighter", "Main Atal Hoon", "Teri Baaton Mein Aisa Uljha Jiya", "Article 370", "Shaitaan", "Yodha", "Madgaon Express", "Swatantrya Veer Savarkar", "Crew", "Maidaan", "Bade Miyan Chote Miyan", "Do Aur Do Pyaar", "Srikanth", "Mr. & Mrs. Mahi", "Munjya", "Chandu Champion", "Ishq Vishk Rebound", "Kalki 2898 AD", "Kill", "Sarfira", "Bad Newz", "Raayan", "Auron Mein Kahan Dum Tha", "Ulajh", "Stree 2", "Khel Khel Mein", "Vedaa", "The Greatest of All Time", "Sector 36", "Yudhra", "Binny and Family", "Devara: Part 1", "CTRL", "Vicky Vidya Ka Woh Wala Video", "Jigra", "Singham Again", "Bhool Bhulaiyaa 3", "The Buckingham Murders", "Emergency", "Baby John", "Chhaava", "Sky Force", "Game Changer", "Welcome to the Jungle", "Sitare Zameen Par", "Ramayana", "War 2", "Pathaan 2", "Tiger vs Pathaan", "Housefull 5", "Jolly LLB 3", "Masti 4", "Raid 2", "No Entry 2", "Son of Sardaar 2", "Border 2", "Toxic", "Thandel", "Kubera", "Vishwambhara", "OG", "Spirit", "Matka", "UI", "King", "Alpha", "Dhoom 4", "Love & War", "Dragon", "Ramayana Part 1", "Ramayana Part 2"
];

export const INDIAN_PERSONALITIES = [
  "Amitabh Bachchan", "Shah Rukh Khan", "Salman Khan", "Aamir Khan", "Akshay Kumar", "Ajay Devgn", "Hrithik Roshan", "Ranbir Kapoor", "Ranveer Singh", "Alia Bhatt", "Deepika Padukone", "Priyanka Chopra", "Katrina Kaif", "Kareena Kapoor", "Anushka Sharma", "Kajol", "Madhuri Dixit", "Rani Mukerji", "Vidya Balan", "Rajinikanth", "Kamal Haasan", "Prabhas", "Allu Arjun", "Yash", "Vijay", "Dhanush", "Sridevi", "Dilip Kumar", "Rajesh Khanna", "Irrfan Khan",
  "Sachin Tendulkar", "MS Dhoni", "Virat Kohli", "Rohit Sharma", "Kapil Dev", "Sunil Gavaskar", "Neeraj Chopra", "PV Sindhu", "Saina Nehwal", "Mary Kom", "Abhinav Bindra", "Viswanathan Anand", "Sunil Chhetri", "Sania Mirza", "Milkha Singh", "Dhyan Chand", "PT Usha", "Sourav Ganguly", "Rahul Dravid", "Hardik Pandya",
  "Narendra Modi", "Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Vallabhbhai Patel", "B.R. Ambedkar", "Subhash Chandra Bose", "Bhagat Singh", "Indira Gandhi", "Atal Bihari Vajpayee", "A.P.J. Abdul Kalam", "Manmohan Singh", "Rahul Gandhi", "Amit Shah", "Arvind Kejriwal", "Yogi Adityanath", "Mamata Banerjee", "Droupadi Murmu", "S. Jaishankar", "Lal Bahadur Shastri", "Rani Laxmibai",
  "Ratan Tata", "Mukesh Ambani", "Gautam Adani", "Anand Mahindra", "Azim Premji", "Narayana Murthy", "Sudha Murty", "Shiv Nadar", "Vikram Sarabhai", "Homi J. Bhabha", "C.V. Raman", "Srinivasa Ramanujan", "Kalpana Chawla", "Sunita Williams", "Jagadish Chandra Bose", "Kailash Satyarthi", "Mother Teresa", "Rabindranath Tagore", "Satyajit Ray", "Amartya Sen",
  "A.R. Rahman", "Lata Mangeshkar", "Kishore Kumar", "Mohammed Rafi", "Asha Bhosle", "Sonu Nigam", "Shreya Ghoshal", "Arijit Singh", "Zakir Hussain", "Pandit Ravi Shankar", "Bhuvan Bam", "CarryMinati", "Sandeep Maheshwari", "Sadhguru", "Baba Ramdev", "Karan Johar", "S.S. Rajamouli", "Koffee with Karan", "The Kapil Sharma Show", "Zakil Khan"
];
