name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Fync/backend

            echo "=== BEFORE DEPLOY ==="
            git log --oneline -1

            git fetch origin
            git reset --hard origin/main

            echo "=== AFTER DEPLOY ==="
            git log --oneline -1

            npm install

            pm2 restart fync-backend

            pm2 status